pullRequests.grouping = [ { name = "all", "filter" = [{"group" = "*"}]} ]
updates.ignore = [
  { groupId = "org.scala-lang", artifactId = "scala3-library_3" },
  { groupId = "org.scala-lang", artifactId = "scala3-compiler_3" },
  { groupId = "org.scala-lang", artifactId = "scala3-interfaces" },
  { groupId = "org.scala-lang", artifactId = "scala-library", version = "/3\\..*/" },
  { groupId = "org.scala-lang", artifactId = "scala-compiler", version = "/3\\..*/" }
]