-- Add former_reference_department and creating_body properties
-- Add or update display properties for file_name_translation, former_reference_department and creating_body properties
-- Add file property values for the Language

INSERT INTO "FileProperty" ("Name", "Description", "FullName", "PropertyType", "Datatype", "Editable", "MultiValue",
                            "PropertyGroup")
VALUES ('former_reference_department', NULL, 'Former reference', 'Supplied', 'text', true, false, 'OptionalMetadata'),
       ('creating_body', NULL, 'Creating body', 'Defined', 'text', true, false, 'OptionalMetadata');


UPDATE "DisplayProperties"
SET "Value" = 'true'
WHERE "PropertyName" = 'file_name_translation'
  AND "Attribute" = 'Active';

UPDATE "DisplayProperties"
SET "Value" = 'Translated title of record'
WHERE "PropertyName" = 'file_name_translation'
  AND "Attribute" = 'Name';

UPDATE "DisplayProperties"
SET "Value" = 'small text'
WHERE "PropertyName" = 'file_name_translation'
  AND "Attribute" = 'ComponentType';

INSERT INTO "DisplayProperties" ("PropertyName", "Attribute", "Value", "AttributeType")
VALUES ('file_name_translation', 'Ordinal', '25', 'integer'),
       ('former_reference_department', 'Name', 'Former reference', 'text'),
       ('former_reference_department', 'Description',
        'Add the reference provided by the department for when it was holding the record.', 'text'),
       ('former_reference_department', 'ComponentType', 'small text', 'text'),
       ('former_reference_department', 'PropertyType', 'Descriptive', 'text'),
       ('former_reference_department', 'Active', 'true', 'boolean'),
       ('former_reference_department', 'Datatype', 'text', 'text'),
       ('former_reference_department', 'Editable', 'true', 'boolean'),
       ('former_reference_department', 'MultiValue', 'false', 'boolean'),
       ('former_reference_department', 'Ordinal', '30', 'integer'),
       ('former_reference_department', 'Summary', 'Former reference', 'text'),
       ('creating_body', 'Name', 'Creating body', 'text'),
       ('creating_body', 'Description',
        'Add where the record is inherited from if it is different to the transferring body.', 'text'),
       ('creating_body', 'ComponentType', 'select', 'text'),
       ('creating_body', 'PropertyType', 'Descriptive', 'text'),
       ('creating_body', 'Active', 'false', 'boolean'),
       ('creating_body', 'Datatype', 'text', 'text'),
       ('creating_body', 'Editable', 'true', 'boolean'),
       ('creating_body', 'MultiValue', 'false', 'boolean'),
       ('creating_body', 'Ordinal', '35', 'integer'),
       ('creating_body', 'Summary', 'Creating body', 'text'),
       ('end_date', 'Summary', 'Date of the record', 'text');

INSERT INTO "FilePropertyValues" ("PropertyName", "PropertyValue", "Default", "Dependencies", "SecondaryValue")
VALUES ('Language', 'Amharic', NULL, NULL, NULL),
       ('Language', 'Arabic and English', NULL, NULL, NULL),
       ('Language', 'Chinese', NULL, NULL, NULL),
       ('Language', 'Chinese and English', NULL, NULL, NULL),
       ('Language', 'Danish and German', NULL, NULL, NULL),
       ('Language', 'Dutch, English and French', NULL, NULL, NULL),
       ('Language', 'Dutch, English, French and Latin', NULL, NULL, NULL),
       ('Language', 'Dutch, French and Italian', NULL, NULL, NULL),
       ('Language', 'Dutch, French, Latin and Spanish', NULL, NULL, NULL),
       ('Language', 'English and French', NULL, NULL, NULL),
       ('Language', 'English, French and German', NULL, NULL, NULL),
       ('Language', 'English, French, German and Italian', NULL, NULL, NULL),
       ('Language', 'English, French, German and Latin', NULL, NULL, NULL),
       ('Language', 'English, French, German and Russian', NULL, NULL, NULL),
       ('Language', 'English, French and Italian', NULL, NULL, NULL),
       ('Language', 'English, French, Italian and Latin', NULL, NULL, NULL),
       ('Language', 'English, French and Latin', NULL, NULL, NULL),
       ('Language', 'English, French and Spanish', NULL, NULL, NULL),
       ('Language', 'English and German', NULL, NULL, NULL),
       ('Language', 'English, German and Italian', NULL, NULL, NULL),
       ('Language', 'English and Greek', NULL, NULL, NULL),
       ('Language', 'English and Italian', NULL, NULL, NULL),
       ('Language', 'English, Italian and Latin', NULL, NULL, NULL),
       ('Language', 'English and Japanese', NULL, NULL, NULL),
       ('Language', 'English and Latin', NULL, NULL, NULL),
       ('Language', 'English and Portuguese', NULL, NULL, NULL),
       ('Language', 'English and Welsh', NULL, NULL, NULL),
       ('Language', 'French', NULL, NULL, NULL),
       ('Language', 'French and Latin', NULL, NULL, NULL),
       ('Language', 'German', NULL, NULL, NULL),
       ('Language', 'German, Italian and Japanese', NULL, NULL, NULL),
       ('Language', 'German, Italian, Latin and Swedish', NULL, NULL, NULL),
       ('Language', 'Italian and Latin', NULL, NULL, NULL),
       ('Language', 'Latin', NULL, NULL, NULL),
       ('Language', 'Miscellaneous', NULL, NULL, NULL),
       ('Language', 'Portuguese', NULL, NULL, NULL),
       ('Language', 'Spanish', NULL, NULL, NULL),
       ('Language', 'Danish', NULL, NULL, NULL),
       ('Language', 'Dutch', NULL, NULL, NULL),
       ('Language', 'Swedish', NULL, NULL, NULL),
       ('Language', 'English and Russian', NULL, NULL, NULL),
       ('Language', 'English and Spanish', NULL, NULL, NULL),
       ('Language', 'English and Norwegian', NULL, NULL, NULL),
       ('Language', 'Italian', NULL, NULL, NULL),
       ('Language', 'Tibetan', NULL, NULL, NULL),
       ('Language', 'Dutch and Japanese', NULL, NULL, NULL),
       ('Language', 'Chinese, English, Malay and Tamil', NULL, NULL, NULL),
       ('Language', 'Chinese and Malay', NULL, NULL, NULL),
       ('Language', 'Chinese, English and Malay', NULL, NULL, NULL),
       ('Language', 'English and Tamil', NULL, NULL, NULL),
       ('Language', 'English and Gaelic', NULL, NULL, NULL),
       ('Language', 'Dutch and English', NULL, NULL, NULL),
       ('Language', 'Arabic', NULL, NULL, NULL),
       ('Language', 'French and German', NULL, NULL, NULL),
       ('Language', 'Dutch and Spanish', NULL, NULL, NULL),
       ('Language', 'English and Swedish', NULL, NULL, NULL),
       ('Language', 'French, German and Latin', NULL, NULL, NULL),
       ('Language', 'English and Icelandic', NULL, NULL, NULL),
       ('Language', 'Dutch and French', NULL, NULL, NULL),
       ('Language', 'Danish and Latin', NULL, NULL, NULL),
       ('Language', 'English and Polish', NULL, NULL, NULL),
       ('Language', 'Arabic, English and French', NULL, NULL, NULL),
       ('Language', 'Norwegian', NULL, NULL, NULL),
       ('Language', 'Divehi and English', NULL, NULL, NULL),
       ('Language', 'Russian', NULL, NULL, NULL),
       ('Language', 'Amharic and English', NULL, NULL, NULL),
       ('Language', 'French and Swedish', NULL, NULL, NULL),
       ('Language', 'English, German and Russian', NULL, NULL, NULL),
       ('Language', 'French and Russian', NULL, NULL, NULL),
       ('Language', 'Italian and Spanish', NULL, NULL, NULL),
       ('Language', 'Malay', NULL, NULL, NULL),
       ('Language', 'Greek', NULL, NULL, NULL),
       ('Language', 'English, Hungarian and Polish', NULL, NULL, NULL),
       ('Language', 'Bulgarian and French', NULL, NULL, NULL),
       ('Language', 'French and Greek', NULL, NULL, NULL),
       ('Language', 'Japanese', NULL, NULL, NULL),
       ('Language', 'English and Miscellaneous', NULL, NULL, NULL),
       ('Language', 'English and Turkish', NULL, NULL, NULL),
       ('Language', 'Persian', NULL, NULL, NULL),
       ('Language', 'English and Persian', NULL, NULL, NULL),
       ('Language', 'Dutch, English, French and German', NULL, NULL, NULL),
       ('Language', 'Turkish', NULL, NULL, NULL),
       ('Language', 'English, French and Russian', NULL, NULL, NULL),
       ('Language', 'Arabic, English and German', NULL, NULL, NULL),
       ('Language', 'Arabic, English, French and Italian', NULL, NULL, NULL),
       ('Language', 'English, Italian, Latin and Turkish', NULL, NULL, NULL),
       ('Language', 'English, French, Latin and Russian', NULL, NULL, NULL),
       ('Language', 'French and Italian', NULL, NULL, NULL),
       ('Language', 'Serbo-Croatian', NULL, NULL, NULL),
       ('Language', 'English and Korean', NULL, NULL, NULL),
       ('Language', 'German and Latin', NULL, NULL, NULL),
       ('Language', 'English and Urdu', NULL, NULL, NULL),
       ('Language', 'Bulgarian and English', NULL, NULL, NULL),
       ('Language', 'French, German and Italian', NULL, NULL, NULL),
       ('Language', 'French, German and Romanian', NULL, NULL, NULL),
       ('Language', 'French and Polish', NULL, NULL, NULL),
       ('Language', 'Romanian', NULL, NULL, NULL),
       ('Language', 'Czech', NULL, NULL, NULL),
       ('Language', 'English and Hungarian', NULL, NULL, NULL),
       ('Language', 'Czech, English, French and Hungarian', NULL, NULL, NULL),
       ('Language', 'Persian and Russian', NULL, NULL, NULL),
       ('Language', 'Arabic, English, Persian and Turkish', NULL, NULL, NULL),
       ('Language', 'Arabic, English and Italian', NULL, NULL, NULL),
       ('Language', 'Dutch and German', NULL, NULL, NULL),
       ('Language', 'English, French and Greek', NULL, NULL, NULL),
       ('Language', 'Danish, English and French', NULL, NULL, NULL),
       ('Language', 'English, French, Portuguese and Spanish', NULL, NULL, NULL),
       ('Language', 'English, French, Italian and Spanish', NULL, NULL, NULL),
       ('Language', 'Dutch, English and Latin', NULL, NULL, NULL),
       ('Language', 'French and Turkish', NULL, NULL, NULL),
       ('Language', 'English, French and Swedish', NULL, NULL, NULL),
       ('Language', 'Danish, English and Latin', NULL, NULL, NULL),
       ('Language', 'Chinese, Latin and Manchu', NULL, NULL, NULL),
       ('Language', 'German and Italian', NULL, NULL, NULL),
       ('Language', 'Dutch and Latin', NULL, NULL, NULL),
       ('Language', 'Greek and Latin', NULL, NULL, NULL),
       ('Language', 'Dutch, French and German', NULL, NULL, NULL),
       ('Language', 'French and Spanish', NULL, NULL, NULL),
       ('Language', 'Dutch, French and Portuguese', NULL, NULL, NULL),
       ('Language', 'Dutch, French and Spanish', NULL, NULL, NULL),
       ('Language', 'Dutch, English, French and Portuguese', NULL, NULL, NULL),
       ('Language', 'Dutch, English and Yiddish', NULL, NULL, NULL),
       ('Language', 'Portuguese and Spanish', NULL, NULL, NULL),
       ('Language', 'Arabic, English and Hebrew', NULL, NULL, NULL),
       ('Language', 'Dutch, English, French and Spanish', NULL, NULL, NULL),
       ('Language', 'Dutch, English and Spanish', NULL, NULL, NULL),
       ('Language', 'English, French and Polish', NULL, NULL, NULL),
       ('Language', 'Polish', NULL, NULL, NULL),
       ('Language', 'English, German, Polish and Russian', NULL, NULL, NULL),
       ('Language', 'English, Hebrew and Polish', NULL, NULL, NULL),
       ('Language', 'English, Italian and Polish', NULL, NULL, NULL),
       ('Language', 'Chinese, English and French', NULL, NULL, NULL),
       ('Language', 'Polish and Russian', NULL, NULL, NULL),
       ('Language', 'Dutch, Portuguese and Yiddish', NULL, NULL, NULL),
       ('Language', 'Ladino', NULL, NULL, NULL),
       ('Language', 'Hebrew, Ladino and Spanish', NULL, NULL, NULL),
       ('Language', 'Hebrew', NULL, NULL, NULL),
       ('Language', 'English, German, Italian and Japanese', NULL, NULL, NULL),
       ('Language', 'Dutch, English and German', NULL, NULL, NULL),
       ('Language', 'Dutch, German and Latin', NULL, NULL, NULL),
       ('Language', 'Czech, English, French and Latin', NULL, NULL, NULL),
       ('Language', 'Hungarian', NULL, NULL, NULL),
       ('Language', 'Estonian', NULL, NULL, NULL),
       ('Language', 'Latvian', NULL, NULL, NULL),
       ('Language', 'Lithuanian', NULL, NULL, NULL),
       ('Language', 'Maltese', NULL, NULL, NULL),
       ('Language', 'Slovakian', NULL, NULL, NULL),
       ('Language', 'Slovenian', NULL, NULL, NULL),
       ('Language', 'Finnish', NULL, NULL, NULL),
       ('Language', 'English, French and Romanian', NULL, NULL, NULL),
       ('Language', 'English, French, German and Serbian', NULL, NULL, NULL),
       ('Language', 'Serbian', NULL, NULL, NULL),
       ('Language', 'Arabic, English, French and Spanish', NULL, NULL, NULL),
       ('Language', 'Arabic and French', NULL, NULL, NULL),
       ('Language', 'French and Portuguese', NULL, NULL, NULL),
       ('Language', 'English, French and Portuguese', NULL, NULL, NULL),
       ('Language', 'English, Portuguese and Spanish', NULL, NULL, NULL),
       ('Language', 'French, Portuguese and Spanish', NULL, NULL, NULL),
       ('Language', 'English and Maltese', NULL, NULL, NULL),
       ('Language', 'Thai', NULL, NULL, NULL),
       ('Language', 'French, Latin and Spanish', NULL, NULL, NULL),
       ('Language', 'English, French, Latin and Spanish', NULL, NULL, NULL),
       ('Language', 'Armenian, Ottoman Turkish, Persian and Spanish', NULL, NULL, NULL),
       ('Language', 'Spanish and Miscellaneous', NULL, NULL, NULL),
       ('Language', 'Armenian, French, Portuguese and Spanish', NULL, NULL, NULL),
       ('Language', 'Dutch, French, Italian and Spanish', NULL, NULL, NULL),
       ('Language', 'Basque, French and Italian', NULL, NULL, NULL),
       ('Language', 'Arabic, Armenian, Persian and Others', NULL, NULL, NULL),
       ('Language', 'Afrikaans and English', NULL, NULL, NULL),
       ('Language', 'Danish and English', NULL, NULL, NULL),
       ('Language', 'Amharic, English and French', NULL, NULL, NULL),
       ('Language', 'English and Thai', NULL, NULL, NULL),
       ('Language', 'English, French, Russian and Spanish', NULL, NULL, NULL),
       ('Language', 'English, German and Japanese', NULL, NULL, NULL),
       ('Language', 'English and Romanian', NULL, NULL, NULL),
       ('Language', 'Hebrew and Latin', NULL, NULL, NULL),
       ('Language', 'Croatian, English and Serbian', NULL, NULL, NULL),
       ('Language', 'English, German, Greek and Spanish', NULL, NULL, NULL),
       ('Language', 'English, Flemish and French', NULL, NULL, NULL),
       ('Language', 'English, Hindi and Tamil', NULL, NULL, NULL),
       ('Language', 'English and Arabic', NULL, NULL, NULL),
       ('Language', 'English, French and Arabic', NULL, NULL, NULL),
       ('Language', 'English and Swahili', NULL, NULL, NULL),
       ('Language', 'English, Hindi and Urdu', NULL, NULL, NULL),
       ('Language', 'English, Danish and German', NULL, NULL, NULL),
       ('Language', 'Danish, English, French and German', NULL, NULL, NULL),
       ('Language', 'Danish, English and German', NULL, NULL, NULL),
       ('Language', 'Basque, English and French', NULL, NULL, NULL),
       ('Language', 'Greek, Italian and Latin', NULL, NULL, NULL),
       ('Language', 'English and others', NULL, NULL, NULL),
       ('Language', 'Various', NULL, NULL, NULL),
       ('Language', 'French and Dutch', NULL, NULL, NULL),
       ('Language', 'French and English', NULL, NULL, NULL),
       ('Language', 'French, Dutch and German', NULL, NULL, NULL),
       ('Language', 'German and French', NULL, NULL, NULL),
       ('Language', 'Dutch, German and French', NULL, NULL, NULL),
       ('Language', 'English, Dutch and French', NULL, NULL, NULL),
       ('Language', 'English, French and Ottoman Turkish', NULL, NULL, NULL);


COMMIT;
