CREATE TABLE IF NOT EXISTS public."FilePropertyValues"
(
    "PropertyName"      text          NOT NULL,
    "PropertyValue"     text          NOT NULL,
    "Default"           boolean,
    "Dependencies"      integer,
    "SecondaryValue"    integer
);

INSERT INTO "FilePropertyValues" ("PropertyName","PropertyValue","Default","Dependencies","SecondaryValue")
VALUES
    ('Language','English',true,NULL,NULL),
    ('RightsCopyright','Crown Copyright',true,NULL,NULL),
    ('LegalStatus','Public Record(s)',true,NULL,NULL),
    ('LegalStatus','Not Public Record(s)',NULL,NULL,NULL),
    ('LegalStatus','Welsh Public Record(s)',NULL,NULL,NULL),
    ('ClosurePeriod','0',true,NULL,NULL),
    ('FoiExemptionCode','open',true,NULL,NULL),
    ('Language','Welsh',NULL,NULL,NULL),
    ('Language','English and Welsh',NULL,NULL,NULL),
    ('RightsCopyright','Non Crown Copyright',NULL,NULL,NULL),
    ('ClosureType','open_on_transfer',true,NULL,NULL),
    ('TitlePublic','True',true,NULL,NULL),
    ('TitlePublic','False',NULL,2,NULL),
    ('ClosureType','closed_for',NULL,3,NULL),
    ('HeldBy','The National Archives, Kew',true,NULL,NULL),
    ('FoiExemptionCode','24',NULL,NULL,NULL),
    ('FoiExemptionCode','26',NULL,NULL,NULL),
    ('FoiExemptionCode','27(1)',NULL,NULL,NULL),
    ('FoiExemptionCode','27(2)',NULL,NULL,NULL),
    ('FoiExemptionCode','29',NULL,NULL,NULL),
    ('FoiExemptionCode','30(1)',NULL,NULL,NULL),
    ('FoiExemptionCode','30(2)',NULL,NULL,NULL),
    ('FoiExemptionCode','34',NULL,NULL,NULL),
    ('FoiExemptionCode','38',NULL,NULL,NULL),
    ('FoiExemptionCode','39',NULL,NULL,NULL),
    ('FoiExemptionCode','40(2)',NULL,NULL,NULL),
    ('FoiExemptionCode','41',NULL,NULL,NULL),
    ('FoiExemptionCode','43',NULL,NULL,NULL),
    ('FoiExemptionCode','44',NULL,NULL,NULL),
    ('DescriptionPublic','True',true,NULL,NULL),
    ('FoiExemptionCode','23',NULL,NULL,NULL),
    ('DescriptionPublic','False',NULL,1,NULL),
    ('FoiExemptionCode','28',NULL,NULL,30),
    ('FoiExemptionCode','31',NULL,NULL,100),
    ('FoiExemptionCode','32',NULL,NULL,20),
    ('FoiExemptionCode','33',NULL,NULL,20),
    ('FoiExemptionCode','35(1)(a)',NULL,NULL,20),
    ('FoiExemptionCode','35(1)(b)',NULL,NULL,20),
    ('FoiExemptionCode','35(1)(c)',NULL,NULL,20),
    ('FoiExemptionCode','35(1)(d)',NULL,NULL,20),
    ('FoiExemptionCode','36',NULL,NULL,20),
    ('FoiExemptionCode','37(1)(a)',NULL,NULL,20),
    ('FoiExemptionCode','37(1)(aa)',NULL,NULL,20),
    ('FoiExemptionCode','37(1)(ac)',NULL,NULL,20),
    ('FoiExemptionCode','37(1)(ad)',NULL,NULL,20),
    ('FoiExemptionCode','37(1)(b)',NULL,NULL,60),
    ('FoiExemptionCode','42',NULL,NULL,20),
    ('FoiExemptionCode','43(1)',NULL,NULL,30),
    ('FoiExemptionCode','43(2)',NULL,NULL,30);

COMMIT;
