CREATE TABLE IF NOT EXISTS public."DisallowedPuids"
(
    "PUID" text   NOT NULL,
    "PUID Description" text NOT NULL,
    "Created Date" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "Modified Date" timestamp with time zone,
    "ConsignmentType" text
);

INSERT INTO "DisallowedPuids" ("PUID","PUID Description","ConsignmentType")
VALUES
    ('fmt/494','Microsoft Office Encrypted Document','standard'),
    ('fmt/754','Microsoft Word Document (Password Protected)','standard'),
    ('fmt/755','Microsoft Word Document Template (Password Protected)','standard'),
    ('fmt/289','WARC Web ARChive file format','standard'),
    ('fmt/329','Shell Archive Format','standard'),
    ('fmt/508','Quarter Inch Cartridge Host Interchange Format','standard'),
    ('fmt/600','eXtensible ARchive format','standard'),
    ('fmt/610','ARJ File Format','standard'),
    ('fmt/613','RAR Archive','standard'),
    ('fmt/614','Windows Imaging Format','standard'),
    ('fmt/625','Apple Disk Copy Image','standard'),
    ('fmt/626','LHA File Format','standard'),
    ('fmt/639','Stuffit Archive File','standard'),
    ('fmt/656','KryoFlux','standard'),
    ('fmt/726','Virtual Disk Image','standard'),
    ('fmt/842','AccessData Custom Content Image','standard'),
    ('fmt/843','AccessData Custom Content Image (Encrypted)','standard'),
    ('fmt/844','Advanced Forensic Format','standard'),
    ('fmt/850','NuFile Exchange Archival Library','standard'),
    ('fmt/866','Apple Safari Webarchive','standard'),
    ('fmt/887','SafeGuard Encrypted Virtual Disk','standard'),
    ('fmt/1070','Preferred Executable Format','standard'),
    ('fmt/1071','Apple Disk Image','standard'),
    ('fmt/1087','FAT Disk Image','standard'),
    ('fmt/1095','PEA Archive Format','standard'),
    ('fmt/1096','FreeArc Archive Format','standard'),
    ('fmt/1097','ZPAQ Archive Format','standard'),
    ('fmt/1098','XZ File Format','standard'),
    ('fmt/1100','yEnc Encoded File','standard'),
    ('fmt/1102','Uuencoded File','standard'),
    ('fmt/1105','Hierarchical File System','standard'),
    ('fmt/1190','Adobe SWC Package','standard'),
    ('fmt/1242','ZFO (Form) File','standard'),
    ('fmt/1243','ZFO (Message) File','standard'),
    ('fmt/1244','ZFO (Sent Message)','standard'),
    ('fmt/1245','ZFO (Proof of Delivery) File','standard'),
    ('fmt/1251','Electronically Certified Document (EDOC)','standard'),
    ('fmt/1252','Raw Flux Image','standard'),
    ('fmt/1281','WARC 1.1','standard'),
    ('fmt/1340','BDOC 1','standard'),
    ('fmt/1341','ASICS','standard'),
    ('fmt/1355','WARC 1.0','standard'),
    ('fmt/1361','Amiga Disk File','standard'),
    ('fmt/1399','DiskDoubler.','standard'),
    ('x-fmt/157','Interchange File','standard'),
    ('x-fmt/219','Alexa Archive File','standard'),
    ('x-fmt/263','ZIP Format','standard'),
    ('x-fmt/265','Tape Archive Format','standard'),
    ('x-fmt/266','GZIP Format','standard'),
    ('x-fmt/267','BZIP Compressed Archive','standard'),
    ('x-fmt/268','BZIP2 Compressed Archive','standard'),
    ('x-fmt/269','ZOO Compressed Archive','standard'),
    ('x-fmt/412','Java Archive Format','standard'),
    ('x-fmt/416','BinHex Binary Text','standard'),
    ('x-fmt/429','MHTML','standard');

COMMIT;
