CREATE TABLE IF NOT EXISTS public."DisallowedPuids"
(
    "PUID" text NOT NULL,
    "PUID Description" text NOT NULL,
    "Created Date" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "Modified Date" timestamp with time zone,
    "Reason" text
);

INSERT INTO "DisallowedPuids" ("PUID","PUID Description","Reason")
VALUES
    ('fmt/494','Microsoft Office Encrypted Document','PasswordProtected'),
    ('fmt/754','Microsoft Word Document','PasswordProtected'),
    ('fmt/755','Microsoft Word Document Template','PasswordProtected'),
    ('fmt/289','WARC Web ARChive file format','Zip'),
    ('fmt/329','Shell Archive Format','Zip'),
    ('fmt/508','Quarter Inch Cartridge Host Interchange Format','Zip'),
    ('fmt/600','eXtensible ARchive format','Zip'),
    ('fmt/610','ARJ File Format','Zip'),
    ('fmt/613','RAR Archive','Zip'),
    ('fmt/614','Windows Imaging Format','Zip'),
    ('fmt/625','Apple Disk Copy Image','Zip'),
    ('fmt/626','LHA File Format','Zip'),
    ('fmt/639','Stuffit Archive File','Zip'),
    ('fmt/656','KryoFlux','Zip'),
    ('fmt/726','Virtual Disk Image','Zip'),
    ('fmt/842','AccessData Custom Content Image','Zip'),
    ('fmt/843','AccessData Custom Content Image (Encrypted)','Zip'),
    ('fmt/844','Advanced Forensic Format','Zip'),
    ('fmt/850','NuFile Exchange Archival Library','Zip'),
    ('fmt/866','Apple Safari Webarchive','Zip'),
    ('fmt/887','SafeGuard Encrypted Virtual Disk','Zip'),
    ('fmt/1070','Preferred Executable Format','Zip'),
    ('fmt/1071','Apple Disk Image','Zip'),
    ('fmt/1087','FAT Disk Image','Zip'),
    ('fmt/1095','PEA Archive Format','Zip'),
    ('fmt/1096','FreeArc Archive Format','Zip'),
    ('fmt/1097','ZPAQ Archive Format','Zip'),
    ('fmt/1098','XZ File Format','Zip'),
    ('fmt/1100','yEnc Encoded File','Zip'),
    ('fmt/1102','Uuencoded File','Zip'),
    ('fmt/1105','Hierarchical File System','Zip'),
    ('fmt/1190','Adobe SWC Package','Zip'),
    ('fmt/1242','ZFO (Form) File','Zip'),
    ('fmt/1243','ZFO (Message) File','Zip'),
    ('fmt/1244','ZFO (Sent Message)','Zip'),
    ('fmt/1245','ZFO (Proof of Delivery) File','Zip'),
    ('fmt/1251','Electronically Certified Document (EDOC)','Zip'),
    ('fmt/1252','Raw Flux Image','Zip'),
    ('fmt/1281','WARC 1.1','Zip'),
    ('fmt/1340','BDOC 1','Zip'),
    ('fmt/1341','ASICS','Zip'),
    ('fmt/1355','WARC 1.0','Zip'),
    ('fmt/1361','Amiga Disk File','Zip'),
    ('fmt/1399','DiskDoubler.','Zip'),
    ('x-fmt/157','Interchange File','Zip'),
    ('x-fmt/219','Alexa Archive File','Zip'),
    ('x-fmt/263','ZIP Format','Zip'),
    ('x-fmt/265','Tape Archive Format','Zip'),
    ('x-fmt/266','GZIP Format','Zip'),
    ('x-fmt/267','BZIP Compressed Archive','Zip'),
    ('x-fmt/268','BZIP2 Compressed Archive','Zip'),
    ('x-fmt/269','ZOO Compressed Archive','Zip'),
    ('x-fmt/412','Java Archive Format','Zip'),
    ('x-fmt/416','BinHex Binary Text','Zip'),
    ('x-fmt/429','MHTML','Zip');

COMMIT;
