ALTER TABLE Consignment DROP FOREIGN KEY Consignment_User_fkey;
ALTER TABLE ConsignmentMetadata DROP FOREIGN KEY ConsignmentMetadata_ibfk_3;
ALTER TABLE File DROP FOREIGN KEY File_ibfk_2;
ALTER TABLE FileMetadata DROP FOREIGN KEY FileMetadata_ibfk_3;

ALTER TABLE Consignment MODIFY COLUMN UserId VARCHAR(40) NOT NULL;
ALTER TABLE ConsignmentMetadata MODIFY COLUMN UserId VARCHAR(40) NOT NULL;
ALTER TABLE File MODIFY COLUMN UserId VARCHAR(40) NOT NULL;
ALTER TABLE FileMetadata MODIFY COLUMN UserId VARCHAR(40) NOT NULL;
