-- Insert data into the DisplayProperties table

INSERT INTO "DisplayProperties" ("PropertyName","Attribute","Value","AttributeType")
VALUES
  ('date_range','Name','Date range','text'),
  ('date_range','PropertyType','Descriptive','text'),
  ('date_range','Active','false','boolean'),
  ('date_range','Datatype','text','text'),
  ('date_range','Editable','true','boolean'),
  ('date_range','MultiValue','false','boolean'),
  ('Filename','Name','Filename','text'),
  ('Filename','Description','The title of the file','text'),
  ('Filename','PropertyType','Descriptive','text'),
  ('Filename','Active','false','boolean'),
  ('Filename','Datatype','text','text'),
  ('Filename','Editable','false','boolean'),
  ('Filename','MultiValue','false','boolean'),
  ('ClosureType','Name','Has this closure been approved by the Advisory Council?','text'),
  ('ClosureType','Description','Has this closure been approved by the Advisory Council?','text'),
  ('ClosureType','Ordinal','10','integer'),
  ('ClosureType','ComponentType','checkbox','text'),
  ('ClosureType','Group','1','text'),
  ('ClosureType','PropertyType','Closure','text'),
  ('ClosureType','Active','true','boolean'),
  ('ClosureType','Label','Yes, I confirm','text'),
  ('ClosureType','Datatype','text','text'),
  ('ClosureType','Editable','true','boolean'),
  ('ClosureType','MultiValue','false','boolean'),
  ('file_name_translation','Name','Translated title of record (optional)','text'),
  ('file_name_translation','Description','If the title is not in English you can provide a translation.','text'),
  ('file_name_translation','ComponentType','large text','text'),
  ('file_name_translation','PropertyType','Descriptive','text'),
  ('file_name_translation','Active','false','boolean'),
  ('file_name_translation','Datatype','text','text'),
  ('file_name_translation','Editable','true','boolean'),
  ('file_name_translation','MultiValue','false','boolean'),
  ('description','Name','Description','text'),
  ('description','Description','This description will be visible on Discovery and help explain the content of your file(s).','text'),
  ('description','Ordinal','10','integer'),
  ('description','ComponentType','large text','text'),
  ('description','Group','1','text'),
  ('description','PropertyType','Descriptive','text'),
  ('description','Active','true','boolean'),
  ('description','Datatype','text','text'),
  ('description','Editable','true','boolean'),
  ('description','MultiValue','false','boolean'),
  ('DescriptionAlternate','Name','Description Alternate','text'),
  ('DescriptionAlternate','ComponentType','large text','text'),
  ('DescriptionAlternate','Group','2','text'),
  ('DescriptionAlternate','PropertyType','Closure','text'),
  ('DescriptionAlternate','Active','true','boolean'),
  ('DescriptionAlternate','Datatype','text','text'),
  ('DescriptionAlternate','Editable','true','boolean'),
  ('DescriptionAlternate','MultiValue','false','boolean'),
  ('ClosurePeriod','Name','Closure Period','text'),
  ('ClosurePeriod','Description','Number of years the record is closed from the closure start date','text'),
  ('ClosurePeriod','Ordinal','15','integer'),
  ('ClosurePeriod','UnitType','Years','text'),
  ('ClosurePeriod','Group','2','text'),
  ('ClosurePeriod','PropertyType','Closure','text'),
  ('ClosurePeriod','Active','true','boolean'),
  ('ClosurePeriod','Guidance','Years','text'),
  ('ClosurePeriod','Datatype','integer','text'),
  ('ClosurePeriod','Editable','true','boolean'),
  ('ClosurePeriod','MultiValue','false','boolean'),
  ('DescriptionClosed','Name','Is the description closed?','text'),
  ('DescriptionClosed','Description','This field cannot be edited here. You can edit the description in the Descriptive metadata step.','text'),
  ('DescriptionClosed','Ordinal','30','integer'),
  ('DescriptionClosed','ComponentType','radial','text'),
  ('DescriptionClosed','Group','2','text'),
  ('DescriptionClosed','PropertyType','Closure','text'),
  ('DescriptionClosed','Active','true','boolean'),
  ('DescriptionClosed','Label','Yes|No, this description can be made public','text'),
  ('DescriptionClosed','Datatype','boolean','text'),
  ('DescriptionClosed','Editable','true','boolean'),
  ('DescriptionClosed','MultiValue','false','boolean'),
  ('TitleAlternate','Name','Alternative title','text'),
  ('TitleAlternate','Description','Alternative title','text'),
  ('TitleAlternate','ComponentType','small text','text'),
  ('TitleAlternate','Group','2','text'),
  ('TitleAlternate','PropertyType','Closure','text'),
  ('TitleAlternate','Active','true','boolean'),
  ('TitleAlternate','Datatype','text','text'),
  ('TitleAlternate','Editable','true','boolean'),
  ('TitleAlternate','MultiValue','false','boolean'),
  ('TitleClosed','Name','Is the title closed?','text'),
  ('TitleClosed','Description','Is the title closed?','text'),
  ('TitleClosed','Ordinal','25','integer'),
  ('TitleClosed','ComponentType','radial','text'),
  ('TitleClosed','Group','2','text'),
  ('TitleClosed','PropertyType','Closure','text'),
  ('TitleClosed','Active','true','boolean'),
  ('TitleClosed','Label','Yes|No, this title can be made public','text'),
  ('TitleClosed','Datatype','boolean','text'),
  ('TitleClosed','Editable','true','boolean'),
  ('TitleClosed','MultiValue','false','boolean'),
  ('FoiExemptionCode','Name','FOI exemption code(s)','text'),
  ('FoiExemptionCode','Description','Add one or more exemption code to this closure. Here is a <a target="_blank" href="https://www.legislation.gov.uk/ukpga/2000/36/contents">full list of FOI codes and their designated exemptions</a>','text'),
  ('FoiExemptionCode','Ordinal','20','integer'),
  ('FoiExemptionCode','Group','2','text'),
  ('FoiExemptionCode','PropertyType','Closure','text'),
  ('FoiExemptionCode','Active','true','boolean'),
  ('FoiExemptionCode','Guidance','Search for FOI Exemption codes','text'),
  ('FoiExemptionCode','Datatype','text','text'),
  ('FoiExemptionCode','Editable','true','boolean'),
  ('FoiExemptionCode','MultiValue','true','boolean'),
  ('FoiExemptionAsserted','Name','FOI decision asserted','text'),
  ('FoiExemptionAsserted','Description','Date of the Advisory Council approval','text'),
  ('FoiExemptionAsserted','Ordinal','5','integer'),
  ('FoiExemptionAsserted','ComponentType','date','text'),
  ('FoiExemptionAsserted','Group','2','text'),
  ('FoiExemptionAsserted','PropertyType','Closure','text'),
  ('FoiExemptionAsserted','Active','true','boolean'),
  ('FoiExemptionAsserted','Guidance','dd|mm|yyyy','text'),
  ('FoiExemptionAsserted','Datatype','datetime','text'),
  ('FoiExemptionAsserted','Editable','true','boolean'),
  ('FoiExemptionAsserted','MultiValue','false','boolean'),
  ('end_date','Name','End date','text'),
  ('end_date','Description','Enter a date or date range of the last meaningful change to this record.','text'),
  ('end_date','ComponentType','date','text'),
  ('end_date','PropertyType','Descriptive','text'),
  ('end_date','Active','false','boolean'),
  ('end_date','Guidance','dd|mm|yyyy','text'),
  ('end_date','Datatype','datetime','text'),
  ('end_date','Editable','true','boolean'),
  ('end_date','MultiValue','false','boolean'),
  ('date_created','Name','Date Created','text'),
  ('date_created','ComponentType','date','text'),
  ('date_created','PropertyType','Descriptive','text'),
  ('date_created','Active','false','boolean'),
  ('date_created','Guidance','dd|mm|yyyy','text'),
  ('date_created','Datatype','datetime','text'),
  ('date_created','Editable','true','boolean'),
  ('date_created','MultiValue','false','boolean'),
  ('start_date','Name','Start date of range (optional)','text'),
  ('start_date','Description','Enter the start date of the range. The date above will be used as the end date of the range.','text'),
  ('start_date','ComponentType','date','text'),
  ('start_date','PropertyType','Descriptive','text'),
  ('start_date','Active','false','boolean'),
  ('start_date','Guidance','dd|mm|yyyy','text'),
  ('start_date','Datatype','datetime','text'),
  ('start_date','Editable','true','boolean'),
  ('start_date','MultiValue','false','boolean'),
  ('ClosureStartDate','Name','Closure Start Date','text'),
  ('ClosureStartDate','Description','This has been defaulted to the last date modified. If this is not correct, amend the field below.','text'),
  ('ClosureStartDate','Ordinal','10','integer'),
  ('ClosureStartDate','ComponentType','date','text'),
  ('ClosureStartDate','Group','2','text'),
  ('ClosureStartDate','PropertyType','Closure','text'),
  ('ClosureStartDate','Active','true','boolean'),
  ('ClosureStartDate','Guidance','dd|mm|yyyy','text'),
  ('ClosureStartDate','Datatype','datetime','text'),
  ('ClosureStartDate','Editable','true','boolean'),
  ('ClosureStartDate','MultiValue','false','boolean'),
  ('Language','Name','Language','text'),
  ('Language','Description','Choose one or more languages used in this record.','text'),
  ('Language','Ordinal','20','integer'),
  ('Language','Group','1','text'),
  ('Language','PropertyType','Descriptive','text'),
  ('Language','Active','true','boolean'),
  ('Language','Guidance','Search for languages','text'),
  ('Language','Datatype','text','text'),
  ('Language','Editable','true','boolean'),
  ('Language','MultiValue','true','boolean'),
  ('file_name_language','Name','File name language','text'),
  ('file_name_language','ComponentType','small text','text'),
  ('file_name_language','PropertyType','Descriptive','text'),
  ('file_name_language','Active','false','boolean'),
  ('file_name_language','Guidance','Search for a language','text'),
  ('file_name_language','Datatype','text','text'),
  ('file_name_language','Editable','true','boolean'),
  ('file_name_language','MultiValue','false','boolean'),
  ('file_name_translation_language','Name','File name translation language','text'),
  ('file_name_translation_language','PropertyType','Descriptive','text'),
  ('file_name_translation_language','Active','false','boolean'),
  ('file_name_translation_language','Guidance','Search for a language','text'),
  ('file_name_translation_language','Datatype','text','text'),
  ('file_name_translation_language','Editable','true','boolean'),
  ('file_name_translation_language','MultiValue','false','boolean');

COMMIT;
