name: Run DB Migrations
on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: 'Environment'
        required: true
        options:
          - intg
          - staging
          - prod
        default: 'intg'
permissions:
  id-token: write

run-name: Run DB Migrations to ${{inputs.environment}}

jobs:
  run-lambda:
    environment: ${{ github.event.inputs.environment }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          persist-credentials: false
      - id: role-name
        env:
          ENVIRONMENT: ${{ github.event.inputs.environment }}
        run: |
          import os
          with open(os.environ['GITHUB_OUTPUT'], 'a') as fh:
            env = os.environ['ENVIRONMENT']
            print(f"role-name=TDRGithubActionsDeployLambda{env.title()}", file=fh)
        shell: python
      - name: Configure AWS credentials for Lambda
        uses: aws-actions/configure-aws-credentials@e7f100cf4c008499ea8adda475de1042d6975c7b # v6.2.0
        with:
          role-to-assume: arn:aws:iam::${{ secrets.ACCOUNT_NUMBER }}:role/${{ steps.role-name.outputs.role-name }}
          aws-region: eu-west-2
          role-session-name: ECRLogin
      - name: Invoke lambda
        env:
          ENVIRONMENT: ${{ github.event.inputs.environment }}
        run: aws lambda invoke --function-name "tdr-database-migrations-${ENVIRONMENT}" out
